# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



State.destroy_all

State.create({state: "AL", stateName: "Alabama", history: "Alabama became a state of the United States of America on December 14, 1819. The United States arranged for Indian Removal after 1830, relocating most Southeast tribes to west of the Mississippi River to what was then called Indian Territory (now Oklahoma). These actions affected the Cherokee, Creek (Muscogee), and Chickasaw, among others. After this, European-American arrived in large numbers, bringing or buying African Americans in the domestic slave trade.
In antebellum Alabama, wealthy planters created large cotton plantations based in the fertile central Black Belt of the upland region, which depended on the labor of enslaved Africans. Tens of thousands of slaves were transported to and sold in the state by slave traders who purchased them in the Upper South. In the mountains and foothills, poorer whites practiced subsistence farming. By 1860 blacks (nearly all slaves) comprised 45 percent of the state's 964,201 people.", url: "https://en.wikipedia.org/wiki/History_of_Alabama"}) 

State.create({state: "AK", stateName: "Alaska", history: "The history of Alaska dates back to the Upper Paleolithic period (around 14,000 BC), when foraging groups crossed the Bering land bridge into what is now western Alaska. At the time of European contact by the Russian explorers, the area was populated by Alaska Native groups. The name \"Alaska\" derives from the Aleut word Alaxsxaq (also spelled Alyeska), meaning \"mainland\" (literally, \"the object toward which the action of the sea is directed\")
The U.S. purchased Alaska from Russia in 1867. In the 1890s, gold rushes in Alaska and the nearby Yukon Territory brought thousands of miners and settlers to Alaska. Alaska was granted territorial status in 1912 by the United States of America.
In 1942, two of the outer Aleutian Islands—Attu and Kiska—were occupied by the Japanese during World War II and their recovery for the U.S. became a matter of national pride. The construction of military bases contributed to the population growth of some Alaskan cities.", url: "https://en.wikipedia.org/wiki/History_of_Alaska"})

State.create({state: "MI", stateName: "Michigan", history: "The history of human activity in Michigan, a U.S. state in the Great Lakes, began with settlement of the western Great Lakes region by Native Americans perhaps as early as 11,000 BCE. The first European to explore Michigan, Étienne Brûlé, came in about 1620. The area was part of Canada (New France) from 1668 to 1763. In 1701, the French officer Antoine de la Mothe Cadillac, along with fifty-one additional French-Canadians, founded a settlement called Fort Pontchartrain du Détroit, now the city of Detroit. When New France was defeated in the French and Indian War, it ceded the region to Britain in 1763. After the British defeat in the American Revolutionary War, the Treaty of Paris (1783) expanded the United States' boundaries to include nearly all land east of the Mississippi River and south of Canada. Michigan was then part of the \"Old Northwest\". From 1787 to 1800, it was part of the Northwest Territory. In 1800, the Indiana Territory was created, and most of the current state Michigan lay within it, with only the easternmost parts of the state remaining in the Northwest Territory. In 1802, when Ohio was admitted to the Union, the whole of Michigan was attached to the Territory of Indiana, and so remained until 1805, when the Territory of Michigan was established.", url: "https://en.wikipedia.org/wiki/History_of_Michigan"})

State.create({state: "MN", stateName: "Minnesota", history: "The history of the U.S. state of Minnesota is shaped by its original Native American residents, European exploration and settlement, and the emergence of industries made possible by the state's natural resources. Minnesota achieved prominence through fur trading, logging, and farming, and later through railroads, and iron mining. While those industries remain important, the state's economy is now driven by banking, computers, and health care.
The earliest known settlers followed herds of large game to the region during the last glacial period. They preceded the Anishinaabe, the Dakota, and other Native American inhabitants. Fur traders from France arrived during the 17th century. Europeans moving west during the 19th century, drove out most of the Native Americans. Fort Snelling, built to protect United States territorial interests, brought early settlers to the area. Early settlers used Saint Anthony Falls for powering sawmills in the area that became Minneapolis, while others settled downriver in the area that became Saint Paul.
Minnesota gained legal existence as the Minnesota Territory in 1849, and became the 32nd U.S. state on May 11, 1858. After the upheaval of the American Civil War and the Dakota War of 1862, the state's economy started to develop when natural resources were tapped for logging and farming. Railroads attracted immigrants, established the farm economy, and brought goods to market. The power provided by St. Anthony Falls spurred the growth of Minneapolis, and the innovative milling methods gave it the title of the \"milling capital of the world\". New industry came from iron ore, discovered in the north, mined relatively easily from open pits, and shipped to Great Lakes steel mills from the ports at Duluth and Two Harbors. Economic development and social changes led to an expanded role for state government and a population shift from rural areas to cities. The Great Depression brought layoffs in mining and tension in labor relations but New Deal programs helped the state. After World War II, Minnesota became known for technology, fueled by early computer companies Sperry Rand, Control Data and Cray. The Twin Cities also became a regional center for the arts with cultural institutions such as the Guthrie Theater, Minnesota Orchestra, and the Walker Art Center.", url: "https://en.wikipedia.org/wiki/History_of_Minnesota"})

State.create({state: "MS", stateName: "Mississippi", history: "The history of the state of Mississippi extends to thousands of years of indigenous peoples. Evidence of their cultures has been found largely through archeological excavations, as well as existing remains of earthwork mounds built thousands of years ago. Native American traditions were kept through oral histories; the Europeans recorded accounts of historic peoples they encountered. Since the late 20th century, there have been increased studies of the Native American tribes and reliance on their oral histories to document their cultures. Their accounts have been correlated with evidence of natural events.
The first European explorers to settle in the area of the present-day state were French colonists, and later some Spanish and English, particularly along the Gulf Coast. European Americans did not enter the territory in great number until the early nineteenth century, and then they brought many enslaved African Americans with them to serve as laborers to develop cotton plantations along major riverfronts. Through the 1830s, the federal government forced most of the native Choctaw and Chickasaw people west of the Mississippi River. White planters developed an economy based on the export of cotton produced by slave labor along the Mississippi and Yazoo rivers. A small elite group of planters controlled most of the richest land, the wealth, and the politics of the state, which seceded from the Union in 1861. Its river cities particularly were sites of extended battles during the Civil War, and there was widespread destruction.
The bottomlands of the Mississippi Delta were still 90% undeveloped after the Civil War. Thousands of migrants, both black and white, entered the area for a chance at land ownership. They sold timber while clearing land to raise money for purchases. During Reconstruction, many freedmen became owners of farms in these areas and by 1900 composed two-thirds of the property owners in the Delta. After white Democrats regained control of the state legislature in the late 19th century, in 1890 they passed a disfranchising constitution, resulting in the exclusion of African Americans from political life until the late 1960s. Most lost their lands due to disenfranchisement, segregation, financial crises, and an extended decline in cotton prices. By 1920 most were landless sharecroppers and tenant farmers. But in the 1940s, some blacks acquired land under low-interest loans in the New Deal; in 1960 Holmes County still had 800 black farmers, the most of any county in the state. The state continued to rely mostly on agriculture and timber into the 20th century, but mechanization and acquisition of properties by megafarms have changed the labor market and economy.
Through the two waves of the Great Migration, hundreds of thousands of rural blacks left the state. As a result, by the 1930s African Americans were a minority of the population for the first time since the early nineteenth century, but they were a majority of the population in many Delta counties. The state had numerous sites of activism related to the Civil Rights Movement, as African Americans sought to re-establish their constitutional rights for access to public facilities, including all state universities, and the ability to register, vote and run for office.
In the 21st century, the state has expanded its medical and professional communities in cities such as Jackson, the capital. The state legislature approved gaming casinos on riverboats on the Mississippi River and along the Gulf Coast, which has led to increases in tourism in these areas, generating revenues for the state.", url: "https://en.wikipedia.org/wiki/History_of_Mississippi"})

State.create({state: "MO", stateName: "Missouri", history: "The history of Missouri begins with settlement of the region by indigenous people during the Paleo-Indian period beginning in about 12,000 BC. Subsequent periods of native life emerged until the 17th century. New France set up small settlements, and in 1803 Napoleonic France sold the area to the U.S. as part of the Louisiana Purchase. Statehood for Missouri came following a compromise in 1820 that allowed slavery. Settlement was rapid after 1820, aided by a network of rivers navigable by steamboats, centered in the dominant city St. Louis. It attracted European immigrants, especially Germans; the business community had a large Yankee element as well. The Civil War saw numerous small battles and control by the Union. After the war, its economy became more diverse, and railroads, centered in Kansas City, opened up new farmlands in the west. In the early 20th century Progressive reforms sought to modernize state and local government and minimize political corruption. During the 20th century, Missouri's economy diversified further, and it developed a balanced agricultural and economic sector. By the 21st century manufacturing was fading, as service industries grew, especially in medicine, education and tourism. Agriculture remained profitable, as the farms grew larger and fewer people lived on them.", url: "https://en.wikipedia.org/wiki/History_of_Missouri"})

State.create({state: "MT", stateName: "Montana", history: "On April 30, 1803, the Louisiana Purchase Treaty was signed by representatives of the U.S. at Paris, France. The United States Senate ratified the treaty on October 20 and President Thomas Jefferson announced the treaty to the American people on July 4, 1803. The area covered by the purchase included much of the present-day United States between the Continental Divide and the Mississippi River, encompassing the Great Plains including part of what is now Montana, particularly the Missouri River drainage. The rights to the Louisiana Purchase territory cost the U.S. $15 million, which came out to an average of 3 cents an acre. On March 10, 1804, a formal ceremony was conducted in St. Louis, Missouri, to transfer ownership of the territory from France to the United States of America. The lands of present-day Montana were practically unknown and too distant from the seats of power for this political boundary change to have much impact upon them, but the Louisiana Purchase would prove a sea-change for the area.", url: "https://en.wikipedia.org/wiki/History_of_Montana"})

State.create({state: "NE", stateName: "Nebraska", history: "The history of the U.S. state of Nebraska dates back to its formation as a territory by the Kansas–Nebraska Act, passed by the United States Congress on May 30, 1854. The Nebraska Territory was settled extensively under the Homestead Act of 1862 during the 1860s, and in 1867 was admitted to the Union as the 37th U.S. state. The Plains Indians were descendants of succeeding cultures of indigenous peoples who have occupied the area for thousands of years.", url: "https://en.wikipedia.org/wiki/History_of_Nebraska"})

State.create({state: "NV", stateName: "Nevada", history: "Nevada became the 36th state on October 31, 1864, after telegraphing the Constitution of Nevada to the Congress days before the November 8 presidential election (the largest and costliest transmission ever by telegraph). Statehood was rushed to help ensure three electoral votes for Abraham Lincoln's reelection and add to the Republican congressional majorities.
Nevada's harsh but rich environment shaped its history and culture. Before 1858 small Mormon settlements existed along the border of Utah, with the western part stumbling along until the great silver strikes beginning in 1858 created boom towns and fabulous fortunes. After the beginning of the 20th century, profits declined while Progressive reformers sought to curb capitalism. They imagined a civilized Nevada of universities, lofty idealism, and social reform. But an economic bust during the 1910s and disillusionment from failures at social reform and a population decline of nearly one-fourth meant that by 1920 Nevada had degenerated into a \"beautiful desert of buried hopes.\" The boom returned when big time gambling arrived in 1931, and with good transportation (especially to California metropolitan areas), the nation's easiest divorce laws, and a speculative get-rich-quick spirit, Nevada had a boom-and-bust economy that was mostly boom until the worldwide financial crisis of 2008 revealed extravagant speculation in housing and casinos on an epic scale.", url: "https://en.wikipedia.org/wiki/History_of_Nevada"})

State.create({state: "NH", stateName: "New Hampshire", history: "The colony that became the state of New Hampshire was founded on the division in 1629 of a land grant given in 1622 by the Council for New England to Captain John Mason (former governor of Newfoundland) and Sir Ferdinando Gorges (who founded Maine). The colony was named New Hampshire by Mason after the English county of Hampshire, one of the first Saxon shires. Hampshire was itself named after the port of Southampton, which was known previously as simply \"Hampton\".
New Hampshire was first settled by Europeans at Odiorne's Point in Rye (near Portsmouth) by a group of fishermen from England under David Thompson in 1623, just three years after the Pilgrims landed at Plymouth. Early historians believed the first native-born New Hampshirite, John Thompson, was born there.", url: "https://en.wikipedia.org/wiki/History_of_New_Hampshire"})

State.create({state: "NJ", stateName: "New Jersey", history: "In the 17th century, the New Jersey region came under the control of the Swedes and the Dutch, resulting in a struggle in which the Dutch proved victorious (1655). However, the English seized the Dutch colony of New Netherland in 1664. New Jersey became one of the Thirteen Colonies which broke away from Britain in the American Revolution, adopting the Declaration of Independence in 1776. Becoming a state upon the formation of the United States, New Jersey saw significant action during the American Revolutionary War. New Jersey's delegates signed the Articles of Confederation in 1779 and Princeton acted as the nation's capital for four months in 1783.
In 1787, New Jersey became the third state to ratify the United States Constitution. In the 19th century, New Jersey cities led the United States into the Industrial Revolution and provided soldiers for many of the wars the United States fought, including 88,000 men for the American Civil War. The state became a component of the Underground Railroad. The state's transportation system continued to improve with the construction of canals and more rail lines that helped industrialization develop further. During the early 20th century New Jersey prospered, but the economy weakened in the Great Depression of the 1930s. During World War II (1939-1945) and the Cold War (c. 1947-1991), New Jersey's shipyards and military bases played an important role in the defense of the United States. In the 1960s New Jersey became the site of several race riots and of the Glassboro Summit Conference (1967), between American President Lyndon B. Johnson and Soviet Premier Alexei Kosygin.", url: "https://en.wikipedia.org/wiki/History_of_New_Jersey"})

State.create({state: "NM", stateName: "New Mexico", history: "The history of New Mexico is based on both archeological evidence, attesting to varying cultures of humans occupying the area of New Mexico since approximately 9200 BC, and written records. The earliest peoples had migrated from northern areas of North America after leaving Siberia via the Bering Land Bridge. Artifacts and architecture demonstrate ancient complex cultures in this region.
The first written records of the region were made by the Spanish Conquistadors, who encountered Native American Pueblos when they explored the area in the 16th century. Since that time, the Spanish Empire, Mexico, and the United States (since 1848) have claimed control of the area.
The area was governed as New Mexico Territory until 1912, when it was admitted as a state. The relatively isolated state had an economy dependent on mining. Its residents and government suffered from a reputation for corruption and extreme traditionalism. New Mexico introduced the atomic age in 1945, as the first nuclear weapons were developed by the federal government in the research center it established at Los Alamos. Ethnically the state has historically been divided among Native American, Hispanic and Anglo elements—the latter mostly migrants from Texas in the early years.", url: "https://en.wikipedia.org/wiki/History_of_New_Mexico"})

State.create({state: "NY", stateName: "New York", history: "The history of New York begins around 10,000 B.C. when the first people arrived. By 1100 A.D. two main cultures had become dominant as the Iroquoian and Algonquian developed. European discovery of New York was led by the Italian Giovanni da Verrazzano in 1524 followed by the first land claim in 1609 by the Dutch. As part of New Netherland, the colony was important in the fur trade and eventually became an agricultural resource thanks to the patroon system. In 1626 the Dutch bought the island of Manhattan from American Indians. In 1664, England renamed the colony New York, after the Duke of York (later James II & VII.) New York City gained prominence in the 18th century as a major trading port in the Thirteen Colonies.
New York played a pivotal role during the American Revolution and subsequent war. The Stamp Act Congress in 1765 brought together representatives from across the Thirteen Colonies to form a unified response to British policies. The Sons of Liberty were active in New York City to challenge British authority. After a major loss at the Battle of Long Island, the Continental Army suffered a series of additional defeats that forced a retreat from the New York City area, leaving the strategic port and harbor to the British army and navy as their North American base of operations for the rest of the war. The Battle of Saratoga was the turning point of the war in favor of the Americans, convincing France to formally ally with them. New York's constitution was adopted in 1777, and strongly influenced the United States Constitution. New York City was the national capital at various times between 1785 and 1790, where the Bill of Rights was drafted. Albany became the permanent state capital in 1797. In 1787, New York became the eleventh state to ratify the United States Constitution.
New York hosted significant transportation advancements in the 19th century, including the first steamboat line in 1807, the Erie Canal in 1825, and America's first regularly scheduled rail service in 1831. These advancements led to the expanded settlement of western New York and trade ties to the Midwest settlements around the Great Lakes.
Due to New York City's trade ties to the South, there were numerous southern sympathizers in the early days of the American Civil War and the mayor proposed secession. Far from any of the battles, New York ultimately sent the most men and money to support the Union cause. Thereafter, the state helped create the industrial age and consequently was home to some of the first labor unions.
During the 19th century, New York City became the main entry point for European immigrants to the United States, beginning with a wave of Irish during their Great Famine. Millions came through Castle Clinton in Battery Park before Ellis Island opened in 1892 to welcome millions more, increasingly from eastern and southern Europe. The Statue of Liberty opened in 1886 and became a symbol of hope. New York boomed during the Roaring Twenties, before the Wall Street Crash of 1929, and skyscrapers expressed the energy of the city. New York City was the site of successive tallest buildings in the world from 1913 to 1974.
The buildup of defense industries for World War II turned around the state's economy from the Great Depression, as hundreds of thousands worked to defeat the Axis powers. Following the war, the state experienced significant suburbanization around all the major cities, and most central cities shrank. The Thruway system opened in 1956, signaling another era of transportation advances.
Following a period of near-bankruptcy in the late 1970s, New York City renewed its stature as a cultural center, attracted more immigration, and hosted the development of new music styles. The city developed from publishing to become a media capital over the second half of the 20th century, hosting most national news channels and broadcasts. Some of its newspapers became nationally and globally renowned. The state's manufacturing base eroded with the restructuring of industry, and the state transitioned into service industries.
The September 11 attacks of 2001 destroyed the World Trade Center, killing almost 3,000 people; they were the largest terrorist attacks on United States soil.", url: "https://en.wikipedia.org/wiki/History_of_New_York_(state)"})

State.create({state: "NC", stateName: "North Carolina", history: "By 1640, some growth took place with colonists migrating from Virginia, who moved into the area of Albemarle Sound. In 1663, the king granted a charter for a new colony named Carolina in honor of his father Charles I. He gave ownership to the Lords Proprietors.
Reconstructed royal governor's mansion, Tryon Palace, in New Bern North Carolina developed a system of representative government and local control by the early 18th century. Many of its colonists resented British attempts after 1756 to levy taxes without representation in Parliament. The colony was a Patriot base during the American Revolution, and its legislature issued the Halifax Resolves, which authorized North Carolina delegates to the Second Continental Congress to vote for independence from Britain. Loyalist elements were suppressed, and there was relatively little military activity until late in the war.
During the first half of the nineteenth century, North Carolina remained a rural state, with no cities and few villages. Most whites operated small subsistence farms, but the eastern part of the state had a growing class of planters, especially after 1800 when cotton became highly profitable due to the invention of the cotton gin, which enabled cultivation of short-staple cotton in the uplands. All cotton cultivation as a commodity crop was dependent on the slave labor of African Americans. Politically the state was highly democratic, as heated elections pitted the Democratic east versus the Whiggish west. After the fire and ensuing battle on Fort Sumter in April 1861, North Carolina seceded from the United States and joined the Confederate States of America. More soldiers from North Carolina fought for the Confederacy during the American Civil War than from any other state, but few major battles were fought here. During the early years of Reconstruction, strides were made at integrating the newly freed slaves into society. Whites regained political power by violence and in 1899, disfranchised blacks through a new constitution, imposing Jim Crow and white supremacy.
The Civil Rights Movement strengthened in the 1950s and 1960s, and it had strong supporters and activists in North Carolina. Events such as the sit-in protest at the F.W. Woolworth's store in Greensboro would become a touchstone for the movement. The Student Nonviolent Coordinating Committee, a central organization in the movement, was founded at Shaw University in Raleigh. Following the passage of national civil rights legislation to enforce suffrage, in 1973, Clarence Lightner was elected in Raleigh as the first African-American mayor of a major southern city.", url: "https://en.wikipedia.org/wiki/History_of_North_Carolina"})

State.create({state: "ND", stateName: "North Dakota", history: "North Dakota was first settled by Native Americans several thousand years ago. The first Europeans explored the area in the 18th century establishing some limited trade with the natives.
Much of the area was first organized by the United States as part of the Minnesota Territory and then the Dakota Territory in the 19th century. North Dakota gained statehood in 1889.
The railroads became the engine of settlement in the state. Its economy has since its early days been heavily based on the production of agricultural products such as wheat, flaxseed, and cattle, however its farming industry has declined and the state has suffered population decline in formerly heavy farming areas.", url: "https://en.wikipedia.org/wiki/History_of_North_Dakota"})

State.create({state: "OH", stateName: "Ohio", history: "By the mid-18th century, a few American and French fur traders engaged historic Native American tribes in present-day Ohio in the fur trade. The Native Americans had their own extensive trading networks across the continent before the Europeans arrived. American settlement in the Ohio Country came after the American Revolutionary War and the formation of the United States, with its takeover of former British territory. Congress prohibited slavery in the Northwest Territory which presaged Ohio and the five states of the Territory entering the Union as free states. Ohio's population increased rapidly after United States victory in the Northwest Indian Wars brought peace to the Ohio frontier. In 1803, Ohio was admitted to the union as the 17th state. Settlement was chiefly by migrants from New England, New York and Pennsylvania. Southerners settled along the southern part of the territory, arriving by travel along the Ohio River from the Upper South. Yankees, especially in the \"Western reserve\" (near Cleveland), supported modernization, public education, and anti-slavery policies. The state supported the Union in the American Civil War, although antiwar Copperhead sentiment was strong in southern settlements.
After the Civil War, Ohio developed as a major industrial state. Ships traveled the Great Lakes to deliver iron ore and other products from western areas. This was also a route for exports, as were the railroads. In the late 19th and early 20th centuries, the fast-growing industries created jobs that employed hundreds of thousands of immigrants from Europe. In World War I Europe was closed off to passenger traffic. A new wave of migrants came from the South, with rural whites from Appalachia, and African Americans in the Great Migration from the Deep South, to escape Jim Crow and violence.
The cultures of Ohio's major cities became much more diverse with the traditions, cultures, foods, and music of the new arrivals. Ohio's industries were integral to American industrial power in the 20th century. In the later 20th century, economic restructuring in steel, railroads, and other heavy manufacturing cost the state many jobs as heavy industry declined. The economy in the 21st century has gradually shifted to depend on service industries such as medicine and education.", url: "https://en.wikipedia.org/wiki/History_of_Ohio"})

State.create({state: "OK", stateName: "Oklahoma", history: "The history of Oklahoma refers to the history of the state of Oklahoma and the land that the state now occupies. Areas of Oklahoma east of its panhandle were acquired in the Louisiana Purchase of 1803, while the Panhandle was not acquired until the U.S. land acquisitions following the Mexican–American War.
Most of Oklahoma was set aside as Indian Territory before the Civil War. It was opened for general settlement around 1890—the \"Sooners\" were settlers who jumped the gun. Statehood came to the poor ranching and farming state in Oklahoma, but soon oil was discovered and new wealth poured in.
Historians David Baird and Danney Goble have searched for the essence of the historical experiences of the people of Oklahoma. They find that, \"The shared experiences of Oklahoma's people over time speak of optimism, innovation, perseverance, entrepreneurialism, common sense, collective courage, and simple decency. Those, not victimization, were the core values.\"", url: "http://en.wikipedia.org/wiki/History_of_Oklahoma"})

State.create({state: "OR", stateName: "Oregon", history: "The history of Oregon, a U.S. state, may be considered in five eras: geologic history, inhabitation by native peoples, early exploration by Europeans (primarily fur traders), settlement by pioneers, and modern development.
The term \"Oregon\" may refer to:
Oregon Country, a large region explored by Americans and the British (and generally known to Canadians as the Columbia District);
Oregon Territory, established by the United States two years after its sovereignty over the region was established by the Oregon Treaty; and
Oregon, a U.S. state since 1859
The history of Oregon, and of the Pacific Northwest, has received little attention from historians, as compared to other regions of the American far west.", url: "https://en.wikipedia.org/wiki/History_of_Oregon"})

State.create({state: "PA", stateName: "Pennsylvania", history: "The history of Pennsylvania begins in 1681 when William Penn received a royal deed from King Charles II of England, although human activity in the region precedes that date. The area was home to the Lenape, Susquehannock, Iroquois, Erie, Shawnee, Arandiqiouia, and other American Indian tribes. Most of these tribes were driven off or reduced to remnants as a result of diseases, such as smallpox, that swept through long before any permanent colonists arrived.
Pennsylvania was colonized by Swedish and Dutch settlers in the 17th century, before the English took control of the colony in 1667. In 1681, William Penn established a colony based on religious tolerance; it was settled by many Quakers along with its chief city Philadelphia, which was also the first planned city. In the mid-eighteenth century, the colony attracted many German and Scots-Irish immigrants.
Pennsylvania played a central role in the American Revolution, and Philadelphia served as the nation's capital for a portion of the 18th century. It was the second most populous state in the country from the 18th century into the 20th century, and Philadelphia was the second most populous city in the nation. Pennsylvania also expanded its borders into northwestern, northeastern, and southwestern Pennsylvania, and Pittsburgh grew into one of America's largest and most prominent cities. The state played an important role in the Union's victory in the American Civil War. After the war, Pennsylvania grew into a Republican stronghold and a major manufacturing and transportation center. After the Great Depression and World War II, Pennsylvania moved towards the service industry and became a swing state.", url: "https://en.wikipedia.org/wiki/History_of_Pennsylvania"})

State.create({state: "RI", stateName: "Rhode Island", history: "In 1638, Anne Hutchinson, William Coddington, John Clarke, Philip Sherman, and other religious dissidents settled on Rhode Island after conferring with Williams, forming the settlement of Portsmouth which was governed by the Portsmouth Compact. The southern part of the island became the separate settlement of Newport after disagreements among the founders.
Dissident Samuel Gorton purchased Indian lands at Shawomet in 1642, precipitating a dispute with the Massachusetts Bay Colony. In 1644, Providence, Portsmouth, and Newport united for their common independence as the Colony of Rhode Island and Providence Plantations, governed by an elected council and president. The King of England granted Gorton a separate charter for his settlement in 1648, and Gorton named the settlement Warwick in honor of the Earl of Warwick who had helped him obtain it. These four settlements were finally united into one colony by the Royal Charter of 1663. Critics at the time sometimes referred to it as \"Rogue's Island\", and Cotton Mather called it \"the sewer of New England\" because of the Colony's willingness to accept people who had been banished from Massachusetts Bay.
In 1686, King James II ordered Rhode Island to submit to the Dominion of New England and its appointed governor Edmund Andros. This suspended the Colony's charter, but Rhode Island managed to retain possession of it throughout the brief duration of the Dominion—until Andros was deposed and the Dominion was dissolved. William of Orange became King after the Glorious Revolution of 1688, and Rhode Island's independent government resumed under the 1663 charter—and that charter was used as the state constitution until 1842.
In 1693, William III and Mary II issued a patent extending Rhode Island's territory to three miles \"east and northeast\" of Narragansett Bay, conflicting with the claims of Plymouth Colony. This resulted in several later transfers of territory between Rhode Island and Massachusetts.", url: "https://en.wikipedia.org/wiki/History_of_Rhode_Island"})

State.create({state: "SC", stateName: "South Carolina", history: "South Carolina was one of the original thirteen states of the United States. European exploration of the area began in April 1540, with the Hernando de Soto expedition, who unwittingly introduced new Eurasian diseases that decimated the local Native American population, because they lacked any immunity. In 1663 the English Crown granted land to eight proprietors of what became the colony. The first settlers came to the Province of Carolina at the port of Charleston in 1670; they were mostly wealthy planters and their slaves coming from the English Caribbean colony of Barbados. They started to develop their commodity crops of sugar and cotton. Pushing back the Native Americans in the Yamasee War (1715–17), colonists next overthrew the proprietors' rule, seeing more direct representation. In 1719, the colony was officially made a crown colony; North Carolina was split off and made into a separate colony in 1729.", url: "https://en.wikipedia.org/wiki/History_of_South_Carolina"})

State.create({state: "SD", stateName: "South Dakota", history: "In 1803, the United States purchased the Louisiana Territory from Napoleon for $11,000,000. The territory included most of the western half of the Mississippi watershed and covered nearly all of present-day South Dakota, except for a small portion in the northeast corner of the state. The region was still largely unexplored and unsettled, and President Thomas Jefferson organized a group commonly referred to as the Lewis and Clark Expedition to explore the newly acquired region over a period of more than two years.", url: "https://en.wikipedia.org/wiki/History_of_South_Dakota"})

State.create({state: "TN", stateName: "Tennessee", history: "In 1795, a territorial census revealed a sufficient population for statehood. A referendum showed a three-to-one majority in favor of joining the Union. Governor Blount called for a constitutional convention to meet in Knoxville, where delegates from all the counties drew up a model state constitution and democratic bill of rights.
The voters chose Sevier as governor. The newly elected legislature voted for Blount and William Cocke as Senators, and Andrew Jackson as Congressman.
Tennessee leaders thereby converted the territory into a new state, with organized government and constitution, before applying to Congress for admission. Since the Southwest Territory was the first Federal territory to present itself for admission to the Union, there was some uncertainty about how to proceed, and Congress was divided on the issue.
Nonetheless, in a close vote on June 1, 1796, Congress approved the admission of Tennessee as the sixteenth state of the Union. They drew its borders by extending the northern and southern borders of North Carolina, with a few deviations, to the Mississippi River, Tennessee's western boundary.", url: })

State.create({state: "TX", stateName: "Texas", history: "The recorded history of Texas begins with the arrival of the first Spanish conquistadors in the region of North America now known as Texas in 1519, who found the region occupied by numerous Native American tribes. The Native Americans' ancestors had been there for more than 10,000 years as evidenced by the discovery of the remains of prehistoric Leanderthal Lady. During the period of recorded history from A.D. 1519 to 1848, all or parts of Texas were claimed by five countries: France, Spain, Mexico, the Republic of Texas, and the United States of America.
The first European base was established in 1680, along the upper Rio Grande river, near modern El Paso, Texas with the exiled Spaniards and Native Americans from the Isleta Pueblo during the Pueblo Revolt, also known as Popé's Rebellion, from today's northern New Mexico. In 1682, René-Robert Cavelier, Sieur de La Salle (1643-1687), established a French colony at Fort Saint Louis, after sailing down and exploring the Mississippi River from New France (modern Canada) and the Great Lakes. He planted this early French presence at Fort Saint Louis near Matagorda Bay, along the Gulf of Mexico coast (near modern Inez, Texas), even before the establishment of New Orleans on the lower Mississippi River. The colony was killed off by Native Americans after three years, but Spanish authorities felt pressed to establish settlements to keep their claim to the land. Several Roman Catholic missions were established in East Texas; they were abandoned in 1691. Twenty years later, concerned with the continued French presence in neighboring Louisiana, Spanish authorities again tried to colonize Texas. Over the next 110 years, Spain established numerous villages, presidios, and missions in the province. A small number of Spanish settlers arrived, in addition to missionaries and soldiers. Spain signed agreements with colonizers from the United States, bordering the province to the northeast ever since their Louisiana Purchase from the Emperor Napoleon I and his French Empire (France) in 1803. When Mexico won its independence from Spain in 1821, Mexican Texas was part of the new nation. To encourage settlement, Mexican authorities allowed organized immigration from the United States, and by 1834, over 30,000 Anglos lived in Texas, compared to 7,800 Mexicans.
After Santa Anna's dissolution of the Constitution of 1824 and his political shift to the right, issues such as lack of access to courts, the militarization of the region's government (e.g., response to Saltillo-Monclova problem), and self-defense issues resulting in the confrontation in Gonzales, public sentiment in Mexican and Anglo Texans turned towards revolution. Santa Anna's invasion of the territory after putting down the rebellion in Zacatecas provoked the conflict of 1836. The Texian forces fought and won the Texas Revolution in 1835–1836.
Although not recognized as such by Mexico, Texas declared itself an independent nation, the Republic of Texas. Attracted by the rich lands for cotton plantations and ranching, tens of thousands of immigrants arrived from the U.S. and from Germany as well. In 1845, Texas joined the United States, becoming the 28th state, when the United States annexed it. Only after the conclusion of the Mexican–American War, with the Treaty of Guadalupe Hidalgo in 1848, did Mexico recognize Texan independence. Texas declared its secession from the United States in 1861 to join the Confederate States of America. Only a few battles of the American Civil War were fought in Texas; most Texas regiments served in the east. When the war ended, the enslaved African Americans were freed. Texas was subject to Reconstruction, a process that left a residue of bitterness among whites. They regained political dominance and passed laws in the late 19th century creating second-class status for blacks in a Jim Crow system of segregation and disenfranchising them in 1901 through passage of a poll tax. Blacks were excluded from the formal political system until after passage of federal civil rights legislation in the mid-1960s.
Cotton, ranching, and farming dominated the economy, with railroad construction after 1870 a major factor in the development of new cities away from rivers and waterways. Toward the end of the 19th century, timber became an important industry in Texas as well. In 1901 a petroleum discovery at Spindletop Hill, near Beaumont, was developed as the most productive oil well the world had ever seen. The wave of oil speculation and discovery that followed came to be known as the \"Oil Boom\", permanently transforming and enriching the economy of Texas. Agriculture and ranching gave way to a service-oriented society after the boom years of World War II. Segregation ended in the 1960s due to federal legislation. Politically, Texas changed from the virtually one-party Democratic state achieved following disenfranchisement, to a highly contested political scene, until 2000 when it was solidly Republican. The economy of Texas has continued to grow rapidly, becoming the second-largest state in population in 1994, and became economically highly diversified, with a growing base in new technology.", url: })

State.create({state: "WI", stateName: "Wisconsin", history: "The history of Wisconsin encompasses the story not only of the people who have lived in Wisconsin since it became a state of the U.S., but also that of the Native American tribes who made their homeland in Wisconsin, the French and British colonists who were the first Europeans to live there, and the American settlers who lived in Wisconsin when it was a territory. Since its admission to the Union on May 29, 1848 as 30th state, Wisconsin has been ethnically heterogeneous, with Yankees being among the first to arrive from New York and New England. They dominated the state's heavy industry, finance, politics and education. Large numbers of European immigrants followed them, including German Americans, mostly between 1850 and 1900, Scandinavians (the largest group being Norwegian Americans) and smaller groups of Belgian Americans, Dutch Americans, Swiss Americans, Finnish Americans, Irish Americans and others; in the 20th century, large numbers of Polish Americans and African Americans came, settling mainly in Milwaukee. Politically the state was predominantly Republican until recent years, when it became more evenly balanced. The state took a national leadership role in the Progressive Movement, under the aegis of Robert M. La Follette, Sr. and his family, who fought the old guard bitterly at the state and national levels. The \"Wisconsin Idea\" called for the use of the higher learning in modernizing government, and the state is notable for its strong network of state universities.", url: })

State.create({state: "WY", stateName: "Wyoming", history: "There is evidence of prehistoric human habitation in the region known today as the U.S. state of Wyoming stretching back roughly 13,000 years. Stone projectile points associated with the Clovis, Folsom and Plano cultures have been discovered throughout Wyoming. Evidence from what is now Yellowstone National Park indicates the presence of vast continental trading networks since around 1000 years ago. The Union Pacific Railroad played a central role in the European settlement of the area. Wyoming became a U.S. territory in 1868 and became the 44th U.S. state in 1890. It was the first state to grant women the right to vote, in 1869 (although it was then still a territory).", url: "https://en.wikipedia.org/wiki/History_of_Wyoming"})

